version: '3'

services:
  subchainvalidator-0-0:
    container_name: subchainvalidator-0-0
    image: theta:latest
    ports:
      - "16900:22"
      - "19888:22"
      - "2205:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.5

  subchainvalidator-0-1:
    container_name: subchainvalidator-0-1
    image: theta:latest
    ports:
      - "2206:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.6

  subchainvalidator-0-2:
    container_name: subchainvalidator-0-2
    image: theta:latest
    ports:
      - "2207:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.7

  subchainvalidator-0-3:
    container_name: subchainvalidator-0-3
    image: theta:latest
    ports:
      - "2208:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.8

  subchainvalidator-1-0:
    container_name: subchainvalidator-1-0
    image: theta:latest
    ports:
      - "16901:22"
      - "19889:22"
      - "2209:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.9

  subchainvalidator-1-1:
    container_name: subchainvalidator-1-1
    image: theta:latest
    ports:
      - "2210:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.10

  subchainvalidator-1-2:
    container_name: subchainvalidator-1-2
    image: theta:latest
    ports:
      - "2211:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.11

  subchainvalidator-1-3:
    container_name: subchainvalidator-1-3
    image: theta:latest
    ports:
      - "2212:22"
    networks:
      thetanet:
        ipv4_address: 10.10.1.12

networks:
  thetanet:
    external:
      name: thetanet
