theta:
  rpcEndpoint: "http://172.25.149.104:16888/rpc"
node:
  skipInitializeTestWallets: true
rpc:
  enabled: true
  httpAddress: "0.0.0.0"
  httpPort: 18888
  wsAddress: "127.0.0.1"
  wsPort: 18889
  timeoutSecs: 600 
  maxConnections: 2048
log:
  levels: "*:debug"